routes/admin.php
<?php

use App\Http\Livewire\Admin\Colors;
use App\Http\Livewire\Admin\Configuration;
use App\Http\Livewire\Admin\Downloads;
use App\Http\Livewire\Admin\Family;
use App\Http\Livewire\Admin\Index;
use App\Http\Livewire\Admin\Language;
use App\Http\Livewire\Admin\Orders;
use App\Http\Livewire\Admin\Products;
use App\Http\Livewire\Admin\Products\Manage;
use App\Http\Livewire\Admin\Requests;
use App\Http\Livewire\Admin\Showcases;
use App\Http\Livewire\Admin\Sizes;
use App\Http\Livewire\Admin\Users;
use App\Http\Livewire\Admin\Version;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/', Index::class)->name('index');
    Route::get('/language', Language::class)->name('language');
    Route::get('/family', Family::class)->name('family');
    Route::get('/colors', Colors::class)->name('colors');
    Route::get('/sizes', Sizes::class)->name('sizes');

    Route::get('/products', Products::class)->name('products.index');
    Route::get('/products/{product}/manage', Manage::class)->name('products.manage');
    Route::get('/version/{version}/manage', Version::class)->name('versions.manage');

    Route::get('/orders', Orders::class)->name('orders');
    Route::get('/users', Users::class)->name('users');
    Route::get('/request', Requests::class)->name('requests');
    Route::get('/downloads', Downloads::class)->name('downloads');
    Route::get('/settings', Configuration::class)->name('settings');
    Route::get('/showcases', Showcases::class)->name('showcases');
    Route::get('/downloads/{subFamily}/items', Downloads\Manage::class)->name('downloads.items');
    Route::get('/showcases/{showcase}/items', \App\Http\Livewire\Admin\Showcases\Manage::class)->name('showcase.items');
});

routes/web.php
<?php

use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Livewire\Auth\Login;
use App\Http\Livewire\Auth\Passwords\Confirm;
use App\Http\Livewire\Auth\Passwords\Email;
use App\Http\Livewire\Auth\Passwords\Reset;
use App\Http\Livewire\Auth\Register;
use App\Http\Livewire\Auth\Verify;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('login', Login::class)
        ->name('login');


Route::get('/',function (){
    return redirect('/'.app()->getLocale());
});



Route::middleware('auth')->group(function () {
    Route::post('logout', LogoutController::class)
        ->name('logout');
});


require __DIR__.'/admin.php';
require __DIR__.'/client.php';

app/Http/Livewire/Admin/Colors.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Color;
use Illuminate\Support\Str;
use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Color as ModelsColors;
use App\Traits\WithSorting;

class Colors extends Component
{
    use WithPagination;
    use WithSorting;

    public $deleteModal = false;
    public $modal =false;

    public $selectedItem;

    public ModelsColors $color;

    protected $rules =[
        'color.name'=>'required|string',
        'color.code'=>'required|string',
    ];

    public function open($action =null, $itemId=null)
    {
        if ($itemId) {
            $this->selectedItem = $itemId;
            $this->color = ModelsColors::find($itemId);
        }
        if ($action === 'delete') {
            $this->deleteModal = true;
        } elseif ($action === 'edit') {
            $this->color->code = "#".$this->color->code;
            $this->modal = true;
        } else {
            $this->color = new ModelsColors;
            $this->modal = true;
        }
    }

    public function cancel()
    {
        $this->modal = false;
        $this->deleteModal = false;
        $this->selectedItem = null;
        $this->color = new ModelsColors;
    }
    public function destroy()
    {
        $this->color->delete();
        $this->cancel();
    }

    public function save()
    {
        $this->validate();
        $this->color->code=str_replace('#', '', $this->color->code);
        $this->color->save();
        $this->cancel();
    }

    public function render()
    {
        return view('livewire.admin.colors', [
            'colors'=>ModelsColors::where('name', 'LIKE', "%{$this->search}%")
            ->orderBy($this->sortField, $this->sortDirection)
            ->paginate($this->perPage)
        ])->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Configuration.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Config as ModelsConfig;
use App\Traits\WithSorting;
use Illuminate\Support\Str;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

class Configuration extends Component
{
    use WithPagination;
    use WithFileUploads;
    use WithSorting;

    public $deleteModal = false;
    public $modal = false;
    public $imgValue = false;
    public $selectedItem;

    public $picture;

    public ModelsConfig $config ;


    protected $rules = [
        'config.name' => 'required|string',
        'config.value'=>'required|string',
        'config.complement'=>'nullable',
        'picture' => 'nullable|image'
    ];

    public function checkData()
    {
        $this->imgValue = !$this->imgValue;
        if($this->imgValue){

            $this->config->value ="IMAGE";
        }

    }
    public function open($action = null, $itemId = null)
    {
        if ($itemId) {
            $this->selectedItem = $itemId;
            $this->config = ModelsConfig::find($itemId);
        }

        if ($action === 'delete') {
            $this->deleteModal = true;
        } elseif ($action === 'edit') {
            $this->modal = true;
        } else {
            $this->config = new ModelsConfig;
            $this->modal = true;
        }
    }

    /**
     * Cerrar modal
     *
     */
    public function cancel()
    {
        $this->modal = false;
        $this->deleteModal = false;
        $this->selectedItem = null;
        $this->config = new ModelsConfig;
    }

    /**
     * Eliminar registro
     *
     */
    public function destroy()
    {
        $this->config->delete();
        // $this->repository->delete($this->selectedItem);

        $this->cancel();
    }

    /**
     * Guardar/Actualizar registro
     *
     */
    public function save()
    {
        $this->validate();

      if($this->picture != null){

          $this->config->value = $this->picture->store('/public/config');
      }
      $this->config->name = Str::upper($this->config->name);
        $this->config->save();

        $this->cancel();
    }

    public function render()
    {
        return view('livewire.admin.configuration', [
            'configurations' => ModelsConfig::where('name', 'LIKE', "%{$this->search}%")
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate($this->perPage)
        ])->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Downloads.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Download;
use App\Models\SubFamily;
use App\Traits\WithSorting;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;
use App\Models\Download as ModelsDownload;
use App\Models\SubFamily as ModelsSubFamily;

class Downloads extends Component
{
    use WithPagination;
    use WithFileUploads;
    use WithSorting;

    public $deleteModal = false;
    public $deleteModalItem = false;
    public $modal = false;
    public $listOpen = false;
    public $selectedItem;
   public $modalItem = false;
   public $itemIdDownload;

    public $picture;
    public $picture2;

    public $downloadItems ;
    public ModelsSubFamily $subFamily ;
    public ModelsDownload $itemDownload;



    public function open($action = null, $itemId = null)
    {
        if ($itemId) {
            $this->selectedItem = $itemId;
            $this->subFamily = ModelsSubFamily::find($itemId);
        }

        if ($action === 'delete') {
            $this->deleteModal = true;
        } elseif ($action === 'edit') {
            $this->picture = $this->download->picture;
            $this->modal = true;
        }elseif($action ==='list'){
            $this->listOpen = true;
            $this->downloadItems = ModelsDownload::where('subfamily_id',$itemId)->get();
        } else {
            $this->subFamily = new ModelsSubFamily;
            $this->modal = true;
        }
    }

    public function openItem($itemId,$action=null)
    {
        if ($action==='delete') {
            $this->selectedItem = $itemId;
            $this->itemDownload = ModelsDownload::find($itemId);
            $this->deleteModalItem=true;
        }else {
            $this->itemIdDownload = $itemId;
            $this->itemDownload = new ModelsDownload;
            $this->modalItem = true;
        }

    }

    /**
     * Cerrar modal
     *
     */
    public function cancel()
    {
        $this->modal = false;
        $this->deleteModal = false;
        $this->selectedItem = null;
        $this->downloadItems = null;
        $this->modalItem = false;
        $this->subFamily = new ModelsSubFamily();
    }

    /**
     * Eliminar registro
     *
     */
    public function destroy()
    {
        $data = Download::where('subfamily_id',$this->itemIdDownload);
        $data->each(function ($item){
            $item->delete();
        });
        $this->subFamily->delete();
        $this->cancel();
    }


    /**
     * Guardar/Actualizar registro
     *
     */
    public function save()
    {
        $this->validate();


        $this->subFamily->image = $this->picture->store('/public/subfamily');
        $this->subFamily->save();

        $this->cancel();
    }

    public function saveItem()
    {
       $this->validate();
        $this->itemDownload->subfamily_id= $this->itemIdDownload;
        $this->itemDownload->file = $this->picture2->store('/public/subfamily/'.$this->itemIdDownload);
        $this->itemDownload->save();
        $this->cancel();
    }

    protected function rules()
    {
        if ($this->modal === true)
            return [
                'subFamily.name' => 'required|string',
                'subFamily.family_id' => 'required|numeric',
                'picture' => 'image',
            ];

        if ($this->modalItem === true)
            return [
                'picture2' => 'image',
                'itemDownload.name'=> 'required|string',
                'itemDownload.reference'=> 'required|string',
            ];
    }

    public function render()
    {
        return view('livewire.admin.downloads',
            [
                'downloads' => SubFamily::with(['family'])->where('name', 'LIKE', "%{$this->search}%")
                    ->orderBy($this->sortField, $this->sortDirection)
                    ->paginate($this->perPage),
                'families'=>\App\Models\Family::all(),

            ])
            ->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Downloads/Manage.php
<?php

namespace App\Http\Livewire\Admin\Downloads;

use App\Models\Download;
use App\Models\Download as ModelsDownload;
use App\Models\SubFamily;
use App\Models\SubFamily as ModelsSubFamily;
use App\Traits\WithSorting;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

class Manage extends Component
{
    use WithPagination;
    use WithFileUploads;
    use WithSorting;

    public $deleteModal = false;
    public $deleteModalItem = false;
    public $modal = false;
    public $listOpen = false;
    public $selectedItem;
    public $modalItem = false;
    public $itemIdDownload;
    public $subFamily;
    public $picture;
    public $picture2;

    public $downloadItems ;
    public ModelsDownload $itemDownload;


    public function openItem($itemId = null,$action=null)
    {
        if ($action==='delete') {
            $this->selectedItem = $itemId;
            $this->itemDownload = ModelsDownload::find($itemId);
            $this->deleteModalItem=true;
        }else {
            $this->itemIdDownload = $itemId;
            $this->itemDownload = new ModelsDownload;
            $this->modalItem = true;
        }

    }

    /**
     * Cerrar modal
     *
     */
    public function cancel()
    {
        $this->modal = false;
        $this->deleteModal = false;
        $this->selectedItem = null;
        $this->downloadItems = null;
        $this->modalItem = false;
        $this->deleteModalItem=false;
    }

    /**
     * Eliminar registro
     *
     */
    public function destroyItem()
    {
        $this->itemDownload->delete();
        $this->cancel();
    }


    /**
     * Guardar/Actualizar registro
     *
     */


    public function saveItem()
    {
        $this->validate();
        $this->itemDownload->subfamily_id= $this->subFamily;
        $this->itemDownload->file = $this->picture2->store('/public/subfamily/'.$this->subFamily);
        $this->itemDownload->save();
        $this->cancel();
    }

    protected function rules()
    {

            return [
                'picture2' => 'image',
                'itemDownload.name'=> 'required|string',
                'itemDownload.reference'=> 'required|string',
            ];
    }

    public function mount($subFamily)
    {
        $this->subFamily = $subFamily;

    }

    public function render()
    {
        return view('livewire.admin.downloads.manage', [
            'items' => Download::where('subfamily_id',$this->subFamily)->get()
        ])
            ->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Family.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Family as ModelsFamily;
use App\Traits\WithSorting;
use Livewire\Component;
use Livewire\WithPagination;

use Illuminate\Support\Str;
use Livewire\WithFileUploads;

class Family extends Component
{
    use WithPagination;
    use WithFileUploads;
    use WithSorting;

    public $deleteModal = false;
    public $modal = false;
    public $selectedItem;

    public $picture;

    public ModelsFamily $family ;


    protected $rules = [
        'family.name' => 'required|string',
        'picture' => 'required'
    ];


    public function open($action = null, $itemId = null)
    {
        if ($itemId) {
            $this->selectedItem = $itemId;
            $this->family = ModelsFamily::find($itemId);
        }

        if ($action === 'delete') {
            $this->deleteModal = true;
        } elseif ($action === 'edit') {
            $this->picture = $this->family->picture;
            $this->modal = true;
        } else {
            $this->family = new ModelsFamily;
            $this->modal = true;
        }
    }

    /**
     * Cerrar modal
     *
     */
    public function cancel()
    {
        $this->modal = false;
        $this->deleteModal = false;
        $this->selectedItem = null;
        $this->family = new ModelsFamily;
    }

    /**
     * Eliminar registro
     *
     */
    public function destroy()
    {
        $this->family->delete();
        // $this->repository->delete($this->selectedItem);

        $this->cancel();
    }

    /**
     * Guardar/Actualizar registro
     *
     */
    public function save()
    {

        $this->family->slug = Str::slug($this->family->name);
        if(!is_string($this->picture) ) {
            $this->rules['picture']="image";
            $this->family->picture = $this->picture->store('/public/family');
        }
        $this->validate();
        $this->family->save();

        $this->cancel();
    }

    public function render()
    {
        return view('livewire.admin.family', [
            'families' => ModelsFamily::where('name', 'LIKE', "%{$this->search}%")
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate($this->perPage)
        ])->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Index.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Index extends Component
{
    public function render()
    {
        return view('livewire.admin.index')
            ->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Requests.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Requests extends Component
{
    public function render()
    {
        return view('livewire.admin.requests')
            ->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Settings.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Settings extends Component
{
    public function render()
    {
        return view('livewire.admin.settings')
            ->layout('layouts.admin');
    }
}

app/Http/Livewire/Client/Adrenalistic.php
<?php

namespace App\Http\Livewire\Client;

use App\Models\Family;
use App\Models\Product;
use App\Models\Version;
use Livewire\Component;

class Adrenalistic extends Component
{
    public  $slug;
    public function mount($slug){
        $this->slug = $slug;
    }


    public function render()
    {
        $family = Family::where('slug',$this->slug)->first()->toArray();

        $products = Product::where('family_id',$family['id'])->pluck('id');

        return view('livewire.client.adrenalistic', [
            'versions' => Version::with(['product','color','size','rate_version'])->whereIn('product_id',$products)->paginate()

        ])->layout('layouts.app');
    }
}

resources/views/livewire/admin/downloads.blade.php
<div>
    <x-slot name="title">Downloads</x-slot>

    <div>
        <x-admin.title title="Listar descargas" subtitle="listado de descargas"/>

        <div class="mt-4">
            <x-admin.breadcrumb page="Listar de descargas"/>
        </div>

        <div class="mt-4">
            <x-admin.alert label="Creación, edición y eliminación de descargas."/>
        </div>

        <div class="mt-4">
            <x-admin.card icon="file-pdf" title="Tabla de descargas">
                <x-admin.button label="Añadir descarga" class="bg-menuitem hover:bg-pink-400" icon="plus"
                                wire:click="open"/>

                <div class="mt-5">
                    <x-admin.table.table>
                        <x-slot name="head">
                            {{-- <x-admin.table.heading sortable>#</x-admin.table.heading> --}}
                            <x-admin.table.heading sortable wire:click="sortBy('name')"
                                                   :direction="$sortField === 'name' ? $sortDirection : null">Nombre
                            </x-admin.table.heading>
                            <x-admin.table.heading sortable wire:click="sortBy('family_id')"
                                                   :direction="$sortField === 'family_id' ? $sortDirection : null">
                                Familia
                            </x-admin.table.heading>
                            <x-admin.table.heading>Acciones</x-admin.table.heading>
                        </x-slot>

                        <x-slot name="body">
                            @forelse($downloads as $key => $download)
                                <x-admin.table.row wire:loading.class="opacity-50">
                                    {{-- <x-admin.table.cell>{{ $key }}</x-admin.table.cell> --}}
                                    <x-admin.table.cell>
                                        <div class="flex items-center">
                                            <div class="flex-shrink-0 h-10 w-10">
                                                <img
                                                    class="h-10 w-10 rounded-full"
                                                    src="{{ Storage::url($download->image) }}"
                                                    alt=""/>
                                            </div>
                                            <div class="ml-4">
                                                <div class="text-sm font-medium text-gray-900">
                                                    {{  $download->name }}
                                                </div>
                                            </div>
                                        </div>
                                    </x-admin.table.cell>
                                    <x-admin.table.cell>
                                        <div class="flex items-center">

                                            <div class="ml-4">
                                                <div class="text-sm font-medium text-gray-900">
                                                    {{  $download->family->name }}
                                                </div>
                                            </div>
                                        </div>
                                    </x-admin.table.cell>
                                    <x-admin.table.cell>
                                        <div class="flex space-x-3">
                                            <x-admin.button wire:click="openItem( {{ $download->id }})"
                                                            class="bg-menuitem hover:bg-pink-400" icon="plus"/>
                                            <a href="{{ route("admin.downloads.items",$download->id) }}" class="text-white bg-indigo-500 hover:bg-indigo-600 px-4 py-2">
                                                <span class="fa fa-list"></span> Lista
                                            </a>
                                            <x-admin.button wire:click="open('delete', {{ $download->id }})"
                                                            class="bg-red-500 hover:bg-pink-600" icon="trash"/>
                                        </div>
                                    </x-admin.table.cell>
                                </x-admin.table.row>
                            @empty
                                <x-admin.table.row>
                                    <x-admin.table.cell colspan="2">
                                        <div class="flex justify-center items-center text-xl font-bold text-gray-500">No
                                            hay resultados...
                                        </div>
                                    </x-admin.table.cell>
                                </x-admin.table.row>
                            @endforelse
                        </x-slot>
                    </x-admin.table.table>

                    <div class="my-3">
                        {{ $downloads->links() }}
                    </div>
                </div>
            </x-admin.card>


        </div>
        <x-admin.modal wire:model="modal" method="save">
            <x-slot name="title">Datos de descarga</x-slot>

            <label class="flex flex-col mt-4">
                <span>Familia</span>
                <select wire:model="subFamily.family_id">
                    <option value="">seleccione una familia</option>
                    @foreach($families as $key=>$family)
                        <option value="{{$family->id}}">{{$family->name}}</option>
                    @endforeach
                </select>
                @error('product.family_id')
                <div class="text-red-700">{{ $message }}</div> @enderror
            </label>
            <label class="flex flex-col mt-4">
                <span>Nombre</span>
                <input type="text" wire:model="subFamily.name">
                @error('Subfamily.name')
                <div class="text-red-700">{{ $message }}</div> @enderror
            </label>


            <x-admin.form.image-field class="" name="picture" wire:model="picture"
                                      :path="url(Storage::url($picture))"/>

            <x-slot name="action">
                <x-admin.button type="submit" label="Guardar" class="ml-4 rounded bg-blue-500 hover:bg-blue-600"
                                icon="save"/>
            </x-slot>
        </x-admin.modal>


        <x-admin.modal wire:model="modalItem" method="saveItem">
            <x-slot name="title">Datos de item</x-slot>
            <label class="flex flex-col mt-4">
                <span>Nombre</span>
                <input type="text" wire:model="itemDownload.name">
                @error('itemDownload.name')
                <div class="text-red-700">{{ $message }}</div> @enderror
            </label>
            <label class="flex flex-col mt-4">
                <span>Reference</span>
                <input type="text" wire:model="itemDownload.reference">
                @error('itemDownload.reference')
                <div class="text-red-700">{{ $message }}</div> @enderror
            </label>

            <x-admin.form.image-field class="" name="picture2" wire:model="picture2"
                                      :path="url(Storage::url($picture2))"/>

            <x-slot name="action">
                <x-admin.button type="submit" label="Guardar" class="ml-4 rounded bg-blue-500 hover:bg-blue-600"
                                icon="save"/>
            </x-slot>
        </x-admin.modal>


        <x-admin.modal wire:model="deleteModal">
            <x-slot name="title">Eliminar ese elemento {{ $selectedItem }}</x-slot>
            <h1 class="text-red-800 text-4xl"> Al confirmar esta accion se eliminaran tambien todos los items
            de la desacarga que esten asociados
            </h1>
            <x-slot name="action">
                <x-admin.button type="button" label="Eliminar" class="ml-4 rounded bg-red-500 hover:bg-pink-600"
                                icon="trash" wire:click="destroy"/>
            </x-slot>
        </x-admin.modal>




    </div>
</div>

resources/views/livewire/admin/family.blade.php
<div>
    <x-slot name="title">Family</x-slot>

    <div>
        <x-admin.title title="Listar familias" subtitle="listado de familias" />

        <div class="mt-4">
            <x-admin.breadcrumb page="Listar de familias" />
        </div>

        <div class="mt-4">
            <x-admin.alert label="Creación, edición y eliminación de familias." />
        </div>

        <div class="mt-4">
            <x-admin.card icon="sitemap" title="Tabla de familias">
                <x-admin.button label="Añadir familia" class="bg-menuitem hover:bg-pink-400" icon="plus" wire:click="open()" />

                <div class="mt-5">
                    <x-admin.table.table>
                        <x-slot name="head">

                            {{-- <x-admin.table.heading sortable>#</x-admin.table.heading> --}}
                            <x-admin.table.heading sortable wire:click="sortBy('name')" :direction="$sortField === 'name' ? $sortDirection : null">Familia</x-admin.table.heading>
                            <x-admin.table.heading>Acciones</x-admin.table.heading>
                        </x-slot>

                        <x-slot name="body">
                            @forelse($families as $key => $family)
                            <x-admin.table.row wire:loading.class="opacity-50" >
                                {{-- <x-admin.table.cell>{{ $key }}</x-admin.table.cell> --}}
                                <x-admin.table.cell >
                                    <div class="flex items-center">
                                        <div class="flex-shrink-0 h-10 w-10">
                                            <img
                                                class="h-10 w-10 rounded-full"
                                                src="{{ Storage::url($family->picture) }}"
                                                alt="" />
                                        </div>
                                        <div class="ml-4">
                                            <div class="text-sm font-medium text-gray-900">
                                                {{  $family->name }}
                                            </div>
                                        </div>
                                    </div>
                                </x-admin.table.cell>
                                <x-admin.table.cell>
                                    <div class="flex space-x-3">
                                        <x-admin.button wire:click="open('edit', {{ $family->id }})" class="bg-menuitem hover:bg-pink-400" icon="edit" />
                                        <x-admin.button wire:click="open('delete', {{ $family->id }})" class="bg-red-500 hover:bg-pink-600" icon="trash" />
                                    </div>
                                </x-admin.table.cell>
                            </x-admin.table.row>
                            @empty
                            <x-admin.table.row>
                                <x-admin.table.cell colspan="2">
                                    <div class="flex justify-center items-center text-xl font-bold text-gray-500">No hay resultados...</div>
                                </x-admin.table.cell>
                            </x-admin.table.row>
                            @endforelse
                        </x-slot>
                    </x-admin.table.table>

                    <div class="my-3">
                        {{ $families->links() }}
                    </div>
                </div>

            </x-admin.card>
        </div>

        <x-admin.modal wire:model="modal" method="save">
            <x-slot name="title">Datos de la familia</x-slot>


            <x-admin.form.image-field class="" name="picture" wire:model="picture"
                                      :path="url(Storage::url($picture))" />
            <label class="flex flex-col mt-4">
                <span>Familia</span>
                <input type="text" wire:model="family.name">
                @error('family.name')
                <div class="text-red-700">{{ $message }}</div> @enderror
            </label>
            <x-slot name="action">
                <x-admin.button type="submit" label="Guardar" class="ml-4 rounded bg-blue-500 hover:bg-blue-600" icon="save" />
            </x-slot>
        </x-admin.modal>

        <x-admin.modal wire:model="deleteModal">
            <x-slot name="title">Eliminar ese elemento {{ $selectedItem }}</x-slot>
            <x-slot name="action">
                <x-admin.button type="button" label="Eliminar" class="ml-4 rounded bg-red-500 hover:bg-pink-600" icon="trash" wire:click="destroy" />
            </x-slot>
        </x-admin.modal>
    </div>
</div>

resources/views/livewire/admin/index.blade.php
<div>
    <x-slot name="title">Panel de inicio</x-slot>
</div>

resources/views/livewire/admin/requests.blade.php
<div>
    <x-slot name="title">Request</x-slot>

    <div>
        <x-admin.title title="Listar pedidos" subtitle="listado de pedidos" />

        <div class="mt-4">
            <x-admin.breadcrumb page="Listar de pedidos" />
        </div>

        <div class="mt-4">
            <x-admin.alert label="Creación, edición y eliminación de pedidos." />
        </div>

        <div class="mt-4">
            <x-admin.card icon="level-up-alt" title="Tabla de pedidos">
                <x-admin.button label="Añadir pedidos" class="bg-menuitem hover:bg-pink-400" icon="plus" />

                {{-- Table here --}}
            </x-admin.card>
        </div>
    </div>
</div>

resources/views/livewire/admin/settings.blade.php
<div>
    {{-- The whole world belongs to you --}}
</div>