routes/admin.php
<?php

use App\Http\Livewire\Admin\Colors;
use App\Http\Livewire\Admin\Configuration;
use App\Http\Livewire\Admin\Downloads;
use App\Http\Livewire\Admin\Family;
use App\Http\Livewire\Admin\Index;
use App\Http\Livewire\Admin\Language;
use App\Http\Livewire\Admin\Orders;
use App\Http\Livewire\Admin\Products;
use App\Http\Livewire\Admin\Products\Manage;
use App\Http\Livewire\Admin\Requests;
use App\Http\Livewire\Admin\Showcases;
use App\Http\Livewire\Admin\Sizes;
use App\Http\Livewire\Admin\Users;
use App\Http\Livewire\Admin\Version;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {
    Route::get('/', Index::class)->name('index');
    Route::get('/language', Language::class)->name('language');
    Route::get('/family', Family::class)->name('family');
    Route::get('/colors', Colors::class)->name('colors');
    Route::get('/sizes', Sizes::class)->name('sizes');

    Route::get('/products', Products::class)->name('products.index');
    Route::get('/products/{product}/manage', Manage::class)->name('products.manage');
    Route::get('/version/{version}/manage', Version::class)->name('versions.manage');

    Route::get('/orders', Orders::class)->name('orders');
    Route::get('/users', Users::class)->name('users');
    Route::get('/request', Requests::class)->name('requests');
    Route::get('/downloads', Downloads::class)->name('downloads');
    Route::get('/settings', Configuration::class)->name('settings');
    Route::get('/showcases', Showcases::class)->name('showcases');
    Route::get('/downloads/{subFamily}/items', Downloads\Manage::class)->name('downloads.items');
    Route::get('/showcases/{showcase}/items', \App\Http\Livewire\Admin\Showcases\Manage::class)->name('showcase.items');
});

routes/web.php
<?php

use App\Http\Controllers\Auth\EmailVerificationController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Livewire\Auth\Login;
use App\Http\Livewire\Auth\Passwords\Confirm;
use App\Http\Livewire\Auth\Passwords\Email;
use App\Http\Livewire\Auth\Passwords\Reset;
use App\Http\Livewire\Auth\Register;
use App\Http\Livewire\Auth\Verify;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('login', Login::class)
        ->name('login');


Route::get('/',function (){
    return redirect('/'.app()->getLocale());
});



Route::middleware('auth')->group(function () {
    Route::post('logout', LogoutController::class)
        ->name('logout');
});


require __DIR__.'/admin.php';
require __DIR__.'/client.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'box',
        'active',
        'category_id',
        'width',
        'large',
        'height',
        'iva',
        'discount',
        'umbral'
    ];

    public function category()
    {
        return $this->hasOne(Category::class);
    }

    public function versions()
    {
        return $this->belongsTo(Version::class);
    }

    public function imageProduct()
    {
        return $this->belongsTo(ImageShowCase::class);
    }

    public function productLanguages()
    {
        return $this->belongsTo(ProductLanguage::class, 'id', 'language_id');
    }

    public function family()
    {
        return $this->belongsTo(Family::class);
    }
}

app/Http/Livewire/Admin/Products.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Product as ModelsProducts;
use App\Models\ProductLanguage;
use App\Models\ProductLanguage as ModelsProductLanguage;
use App\Traits\WithSorting;
use Livewire\Component;
use Livewire\WithPagination;

class Products extends Component
{
    use WithPagination;
    use WithSorting;

    public $deleteModal = false;
    public $modal = false;
    public $editAction = false;
    public $flag=false;

    public $selectedItem;

    public ModelsProducts $product;
    public ModelsProductLanguage $productLanguage;

    protected $rules = [
        'product.name' => 'required|string',
        'product.box' => 'required|numeric',
        'product.width' => 'required|numeric',
        'product.large' => 'required|numeric',
        'product.height' => 'required|numeric',
        'product.iva' => 'required|numeric',
        'product.discount' => 'required|numeric',
        'product.umbral' => 'required|numeric',
        'product.family_id' => 'required',
        'product.category_id' => 'nullable',

    ];

    public function open($action = null, $itemId = null)
    {
        if ($itemId) {
            $this->selectedItem = $itemId;
            $this->product = ModelsProducts::find($itemId);
        }

        if ($action === 'delete') {
            $this->deleteModal = true;
        } elseif ($action === 'edit') {
            $this->editAction = true;
            $this->product->height = ($this->product->height / 100);
            $this->product->width = ($this->product->width / 100);
            $this->product->large = ($this->product->large / 100);
            $this->modal = true;
            $this->flag=false;
        } else {
            $this->product = new ModelsProducts;
            $this->product->umbral = 2;
            $this->product->discount = 0;
            $this->modal = true;
            $this->flag=true;
        }
    }

    public function destroy()
    {
        $this->product->active =! $this->product->active;
        $this->product->save();
        $this->cancel();
    }

    public function cancel()
    {
        $this->flag=false;
        $this->modal = false;
        $this->deleteModal = false;
        $this->selectedItem = null;
        $this->product = new ModelsProducts;
    }

    public function save($flag = false)
    {
        $this->validate();
        $this->product->height = ($this->product->height * 100);
        $this->product->width = ($this->product->width * 100);
        $this->product->large = ($this->product->large * 100);
        $this->product->umbral = 2;
        $this->product->save();
        $prod = $this->product->id;

        $language = \App\Models\Language::all();
        if ($this->flag) {
            $language->each(function ($item) use ($prod) {
                $this->productLanguage = new ModelsProductLanguage;
                $this->productLanguage->product_id = $prod;
                $this->productLanguage->language_id = $item->id;
                $this->productLanguage->save();
            });
        }

        $this->cancel();
    }

    public function sortBy($field)
    {
        if ($this->sortField === $field) {
            $this->sortDirection = $this->sortDirection === 'asc' ? 'desc' : 'asc';
        } else {
            $this->sortDirection = 'asc';
        }
        $this->sortField = $field;
    }

    public function render()
    {
        return view('livewire.admin.products', [
            'products' => ModelsProducts::with('family')->where('name', 'LIKE', "%{$this->search}%")
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate($this->perPage),
            'families' => \App\Models\Family::all()
        ])
            ->layout('layouts.admin');
    }
}

app/Http/Livewire/Admin/Products/Manage.php
<?php

namespace App\Http\Livewire\Admin\Products;

use App\Models\Color;
use App\Models\Language;
use App\Models\Product;
use App\Models\ProductLanguage;
use App\Models\ProductLanguage as ModelsProductLanguage;
use App\Models\Size;
use App\Models\Version as ModelsVersion;
use App\Models\RateVersion as ModelsRateVersion;
use App\Models\Version;
use App\Traits\WithSorting;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

class Manage extends Component
{
    use WithPagination;
    use WithSorting;
    use WithFileUploads;

    public $deleteModal = false;
    public $modalLanguage =false;
    public $modalVersion =false;

    public $selectedItem;
    public ModelsVersion $version;
    public ModelsProductLanguage $pLanguage;
    public $product;
    public $picture;

    public function mount(Product $product)
    {
        $this->product = $product;
    }


    protected $rules =[
        'pLanguage.description'=>'string',
        'pLanguage.meta_title'=>'string',
        'pLanguage.meta_keys'=>'string',
        'pLanguage.meta_description'=>'string',
        'version.stock'=>'required|numeric',
        'version.weight'=>'required|numeric',
        'version.battery'=>'string',
        'version.material'=>'string',
        'version.reference'=>'required|string',
        'version.type'=>'required',
        'version.video'=>'string',
        'version.size_id'=>'required|numeric',
        'version.color_id'=>'required|numeric',
        'version.product_id'=>'numeric',
        'picture'=>'required',

    ];

    public function openVersion($action =null,$itemId=null)
    {

        if ($itemId) {
            $this->selectedItem = $itemId;
            $this->version = Version::find($itemId);
        }

        if ($action === 'delete') {
            $this->deleteModal = true;
        } elseif ($action === 'edit') {
            $this->picture= $this->version->photo;
            $this->modalVersion = true;
        } else {
            $this->version= new ModelsVersion;
            $this->version->product_id=$this->product->id;
            $this->modalVersion = true;
        }

    }

    public function openProductLanguage($itemId=null)
    {

        $this->selectedItem = $itemId;
        $this->pLanguage = ProductLanguage::find($itemId);
        $this->modalLanguage = true;

    }


    public function cancel()
    {
        $this->modalLanguage = false;
        $this->deleteModal = false;
        $this->modalVersion =false;
        $this->selectedItem = null;
        $this->pLanguage = new ModelsProductLanguage;
    }
    public function destroy()
    {
        $this->version->active = !$this->version->active;
        $this->version->save();
        $this->cancel();
    }

    public function saveLanguage()
    {
        $this->validate();
        $this->pLanguage->save();
        $this->cancel();
    }

    public function saveVersion()
    {
        if(!is_string($this->picture) ) {
            $this->rules['picture'] = "image";
            $this->version->photo = $this->picture->store('/public/version');
        }
        $this->validate();
        $this->version->save();
        $version = $this->version->id;

        $rates = \App\Models\Rate::all();

        $rates->each(function ($item) use($version){
            $this->rateVersion = new ModelsRateVersion;
            $this->rateVersion->version_id = $version;
            $this->rateVersion->rate_id = $item->id;
            $this->rateVersion->save();
        });

        $this->cancel();
    }

    public function render()
    {
        return view('livewire.admin.products.manage', [
            'versions' => Version::with(['color','size'])->where('product_id', $this->product->id)
                ->orderBy($this->sortField, $this->sortDirection)
                ->paginate($this->perPage),
            'languages' => ProductLanguage::with('language')
                ->where('product_id',$this->product->id)
                ->get(),
            'sizes'=>Size::all(),
            'colors'=>Color::all()
        ])->layout('layouts.admin');

    }
}

app/Http/Livewire/Client/Product.php
<?php

namespace App\Http\Livewire\Client;

use App\Models\CartItem;
use App\Models\Gallery;
use App\Models\Language;
use App\Models\ProductLanguage;
use App\Models\Version;
use Illuminate\Support\Facades\DB;
use Livewire\Component;

class Product extends Component
{
    public $version;

    private $productLang;

    // public $items;

    public $gallery;

    public $prodQuantity;

    public $email;

    public function addToCart()
    {
        if ($this->prodQuantity>0) {
            CartItem::updateOrCreate(
                ['cart_id' => auth()->user()->cart->id, 'version_id'=>$this->version->id],
                [
                    'quantity' => DB::raw("quantity + {$this->prodQuantity}"),
                    'price' => $this->version->rateVersion->price
                ]
            );
        }
    }

    public function avisame()
    {
        //guardar email $this->email;
    }

    public function mount($id)
    {
        $languageId = Language::where('locale', app()->getLocale())->first();

        $this->version = Version::with(['product'])->find($id)->first();
        $this->productLang = ProductLanguage::where('language_id', $languageId->id)->where('product_id', $this->version->product->id);

        $this->version->language = $this->productLang->first()->toArray();
        $this->gallery = \App\Models\Gallery::where('version_id', $id)->get();
    }

    public function render()
    {
        return view('livewire.client.product', [
            'items' => CartItem::with(['version'])->where('cart_id', auth()->user()->cart->id)->orderBy('id', 'desc')->get()
        ])->layout('layouts.app');
    }
}

resources/views/livewire/admin/products/manage.blade.php
<div>
    <x-slot name="title">Versión de productos</x-slot>

    <div>
        <x-admin.title title="Gestionar versiones producto" subtitle="Gestionar versiones"/>

        <div class="mt-4">
            <x-admin.breadcrumb page="Gestionar versión"/>
        </div>

        <div class="mt-4">
            <x-admin.alert label="Gestion de versión producto."/>
        </div>

        <div class="mt-4">
            <div class="mt-4">
                <x-admin.card icon="gift" title="Idiomas del producto">
                    <div class="flex justify-between items-center text-xl font-bold text-gray-500 mb-4">
                        <h5>para agregar idioma al producto de click en el icono de la bandera del lenguaje que quieras
                            agregar y/o editar</h5>
                        <br>
                    </div>
                    <div class="flex justify-between items-center text-xl font-bold text-gray-500">
                        @forelse($languages as $key => $language)
                            <img
                                wire:click="openProductLanguage({{$language->id}})"
                                class="h-6 w-8 lg:bg-cover"
                                src="{{ asset("/img/flags/".$language->language->locale.".png") }}"
                                alt="" style="
                            @if(empty($language->description))
                                filter: grayscale(100%);
                            @else
                                filter: grayscale(0);
                            @endif
                                "/>
                        @empty
                            No hay resultados...
                        @endforelse
                    </div>

                </x-admin.card>
            </div>
        </div>

        <div class="mt-4">
            <x-admin.card icon="gift" title="Tabla de gestión de versiones de producto">
                <x-admin.button label="Añadir modelo" class="bg-menuitem hover:bg-pink-400" icon="plus"
                                wire:click="openVersion()"/>

                <x-admin.table.table>
                    <x-slot name="head">
                        {{-- <x-admin.table.heading sortable>#</x-admin.table.heading> --}}
                        <x-admin.table.heading>
                            Foto
                        </x-admin.table.heading>
                        <x-admin.table.heading>
                            Color
                        </x-admin.table.heading>
                        <x-admin.table.heading>
                            Talla
                        </x-admin.table.heading>
                        <x-admin.table.heading sortable wire:click="sortBy('material')"
                                               :direction="$sortField === 'material' ? $sortDirection : null">
                            Material
                        </x-admin.table.heading>
                        <x-admin.table.heading>
                            Ref
                        </x-admin.table.heading>
                        <x-admin.table.heading>
                            Bateria
                        </x-admin.table.heading>
                        <x-admin.table.heading>
                            Stock
                        </x-admin.table.heading>
                        <x-admin.table.heading>Acciones</x-admin.table.heading>
                    </x-slot>

                    <x-slot name="body">
                        @forelse($versions as $key => $version)
                            <x-admin.table.row wire:loading.class="opacity-50">
                                {{-- <x-admin.table.cell>{{ $key }}</x-admin.table.cell> --}}
                                <x-admin.table.cell>
                                    <div class=" h-10 w-10">
                                        <img
                                            class="h-10 w-10 rounded-full"
                                            src="{{ Storage::url($version->photo) }}"
                                            alt=""/>
                                    </div>
                                </x-admin.table.cell>

                                <x-admin.table.cell>{{ $version->color->name ?? ""}} </x-admin.table.cell>

                                <x-admin.table.cell>{{ $version->size->size ??"" }}</x-admin.table.cell>

                                <x-admin.table.cell>{{ $version->material }}</x-admin.table.cell>

                                <x-admin.table.cell>{{ $version->reference }}</x-admin.table.cell>

                                <x-admin.table.cell>{{ $version->battery }}</x-admin.table.cell>

                                <x-admin.table.cell>{{ $version->stock }}</x-admin.table.cell>

                                <x-admin.table.cell>
                                    <div class="flex space-x-3">
                                        <x-admin.button label="editar" wire:click="openVersion('edit', {{ $version->id }})"
                                                        class="bg-menuitem hover:bg-pink-400" icon="edit"/>
                                        <a href="{{ route('admin.versions.manage', $version->id) }}" class="text-white bg-indigo-500 hover:bg-indigo-600 px-4 py-2">
                                            <span class="fa fa-cog"></span> gestionar
                                        </a>

                                        @if($version->active)
                                        <x-admin.button label="desactivar" wire:click="openVersion('delete', {{ $version->id }})"
                                                        class="bg-red-500 hover:bg-pink-600" icon="times-circle"/>
                                        @else
                                            <x-admin.button label="activar" wire:click="openVersion('delete', {{ $version->id }})"
                                                            class="bg-yellow-700 hover:bg-yellow-800" icon="redo"/>
                                        @endif
                                    </div>
                                </x-admin.table.cell>
                            </x-admin.table.row>
                        @empty
                            <x-admin.table.row>
                                <x-admin.table.cell colspan="8">
                                    <div class="flex justify-center items-center text-xl font-bold text-gray-500">No hay
                                        resultados...
                                    </div>
                                </x-admin.table.cell>
                            </x-admin.table.row>
                        @endforelse
                    </x-slot>
                </x-admin.table.table>
                <div class="my-3">
                    {{ $versions->links() }}
                </div>
            </x-admin.card>
        </div>

        <x-admin.modal wire:model="deleteModal">
            <x-slot name="title">Ejecutar operación</x-slot>
            <x-slot name="action">
                <x-admin.button type="button" label="Ejecutar" class="ml-4 rounded bg-blue-500 hover:bg-blue-600"
                                icon="" wire:click="destroy"/>
            </x-slot>
        </x-admin.modal>

        <x-admin.modal wire:model="modalVersion" method="saveVersion">
            <x-slot name="title">Datos de version</x-slot>
            <div class="m-2">
                <h3>Nombre del producto: <strong>{{$product->name}}</strong></h3>
            </div>
            <x-admin.form.image-field class="" name="picture" wire:model="picture"
                                      :path=" url(Storage::url($picture))"/>

            <div class="grid grid-cols-2 gap-2">

                <input type="hidden"  wire:model="version.product_id">

                <label class="flex flex-col mt-4">
                    <span>Talla</span>
                    <select wire:model="version.size_id">
                        <option value="">seleccione una talla</option>
                        @foreach($sizes as $key=>$size)
                            <option value="{{$size->id}}">{{$size->size}}</option>
                        @endforeach
                    </select>
                    @error('version.size_id')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>
                <label class="flex flex-col mt-4">
                    <span>Seleccione un color</span>
                    <select wire:model="version.color_id">
                        <option value="">seleccione un color</option>
                        @foreach($colors as $key=>$color)
                            <option value="{{$color->id}}"
                                    style="background-color: {{"#".$color->code}}">{{$color->name}}</option>
                        @endforeach
                    </select>
                    @error('version.color_id')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>
                <label class="flex flex-col mt-4">
                    <span>Stock</span>
                    <input type="text" wire:model="version.stock">
                    @error('version.stock')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>
                <label class="flex flex-col mt-4">
                    <span>Referencia</span>
                    <input type="text" wire:model="version.reference">
                    @error('version.reference')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>
            </div>

            <div class="grid grid-cols-2 gap-2">
                <label class="flex flex-col mt-4">
                    <span>Peso</span>
                    <input type="text" wire:model="version.weight">
                    @error('version.weight')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>
                <label class="flex flex-col mt-4">
                    <span>Material</span>
                    <input type="text" wire:model="version.material">
                    @error('version.material')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>
                <label class="flex flex-col mt-4">
                    <span>Bateria</span>
                    <input type="text" wire:model="version.battery">
                    @error('version.battery')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>
                <label class="flex flex-col mt-4">
                    <span>video</span>
                    <input type="text" wire:model="version.video">
                </label>
                <label class="flex flex-col mt-4">
                    <span>video</span>
                    <select wire:model="version.type">
                        <option value="">seleccione un tipo</option>
                            <option value="version" selected="selected">version</option>
                        <option value="pack" >pack</option>
                    </select>
                    @error('version.type')
                    <div class="text-red-700">{{ $message }}</div> @enderror
                </label>

            </div>

            <x-slot name="action">
                <x-admin.button type="submit" label="Guardar" class="ml-4 rounded bg-blue-500 hover:bg-blue-600"
                                icon="save"/>
            </x-slot>
        </x-admin.modal>

        <x-admin.modal wire:model="modalLanguage" method="saveLanguage">
            <x-slot name="title">Agregar datos de lenguaje para el producto {{ $selectedItem }}</x-slot>
            <label class="flex flex-col mt-4">
                <span>Descripci&oacute;n</span>
                <input type="text" wire:model="pLanguage.description">
            </label>
            <label class="flex flex-col mt-4">
                <span>Metatitulo</span>
                <input type="text" wire:model="pLanguage.meta_title">

            </label>
            <label class="flex flex-col mt-4">
                <span>MetaKey</span>
                <input type="text" wire:model="pLanguage.meta_keys">

            </label>
            <label class="flex flex-col mt-4">
                <span>MetaDescription</span>
                <input type="text" wire:model="pLanguage.meta_description">

            </label>
            <x-slot name="action">
                <x-admin.button type="submit" label="Guardar" class="ml-4 rounded bg-blue-500 hover:bg-blue-600"
                                icon="save"/>

            </x-slot>
        </x-admin.modal>

    </div>
</div>